### ISSUE TITLE
Release distribution

### ISSUE THREAD

**Issue by Armaldio** [TheRealDannyyy/Construct-3-Desktop-Simple-Launcher#1]
I recommend distributing releases using the release tab
- People get notified on release
- People are used to release tab instead of searching the repo files

**Comment by TheRealDannyyy** [comment]
Release distribution is only gonna happen on the forum. Subbing to the topic will send a notification. Nobody should even come here in the first place.

Releases are under 100mb, so it's more convenient this way as well. Should this change, I will consider using it.
